
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"

branches:
  only:
    - "master"
    - /v.*$/

install:
  - sudo pip3 install --progress-bar off  .
  - sudo pip3 install --progress-bar off mypy
  - sudo pip3 install --progress-bar off sphinx

script:
  - make doc
  - make mypy
  - make test

cache: pip
