
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "pypy3"

os:
  - linux
  - osx
  - windows

branches:
  only:
    - "master"
    - /v.*$/

install: ./.travis.install.sh

script:
  - make doc
  - make mypy
  - make test

cache: pip
